cd into android

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -46,6 +46,7 @@ workflows:
                 # debug log
                 set -x
 
+                cd android
                 bundle install && bundle exec fastlane android distribute_to_firebase
       - cache-push@2: { }
       - deploy-to-bitrise-io@2: { }
@@ -156,6 +157,7 @@ workflows:
                 set -o pipefail
                 # debug log
                 set -x
+                
                 echo version code -- $versionCode
                 echo version name -- $versionName
       - flutter-build@0:
@@ -165,6 +167,20 @@ workflows:
             - android_output_type: appbundle
             - additional_build_params: --build-number=$BUILD_NUMBER --build-name=$versionName --flavor prod
             - is_debug_mode: "true"
+      - script@1:
+          title: Send to firebase
+          inputs:
+            - content: |
+                #!/usr/bin/env bash
+                # fail if any commands fails
+                set -e
+                # make pipeline return status equal the last command to exit with a non-zero status, or zero if all commands exit successfully
+                set -o pipefail
+                # debug log
+                set -x
+
+                cd android
+                bundle install && bundle exec fastlane android distribute_to_play_store
       - cache-pull@2: { }
       - cache-push@2: { }
       - deploy-to-bitrise-io@2: { }
