Update bitrise.yml

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -1,27 +1,9 @@
 ---
 format_version: '11'
-default_step_lib_source: 'https://github.com/bitrise-io/bitrise-steplib.git'
+default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
 project_type: flutter
 workflows:
-  deploy:
-    description: >
-      Builds and deploys app using [Deploy to bitrise.io
-      Step](https://devcenter.bitrise.io/en/getting-started/getting-started-with-flutter-apps.html#deploying-a-flutter-app).
-
-
-      If you build for iOS, make sure to set up code signing secrets on Bitrise
-      for a successful build.
-
-
-      Next steps:
-
-      - Check out [Getting started with Flutter
-      apps](https://devcenter.bitrise.io/en/getting-started/getting-started-with-flutter-apps.html)
-      for signing and deployment options.
-
-      - Check out the [Code signing
-      guide](https://devcenter.bitrise.io/en/code-signing.html) for iOS and
-      Android
+  debug:
     steps:
     - git-clone@6: {}
     - flutter-installer@0:
@@ -29,29 +11,53 @@ workflows:
         - is_update: 'false'
     - flutter-analyze@0:
         inputs:
-        - project_location: $BITRISE_FLUTTER_PROJECT_LOCATION
+        - project_location: "$BITRISE_FLUTTER_PROJECT_LOCATION"
     - flutter-build@0:
         inputs:
-        - project_location: $BITRISE_FLUTTER_PROJECT_LOCATION
+        - project_location: "$BITRISE_FLUTTER_PROJECT_LOCATION"
         - platform: android
-        - android_additional_params: '--debug'
+        - android_additional_params: "--debug"
         - is_debug_mode: 'true'
+        is_always_run: true
     - cache-push@2: {}
     - deploy-to-bitrise-io@2: {}
-  primary:
-    description: >
-      Builds project and runs tests.
-
-
-      Next steps:
-
-      - Check out [Getting started with Flutter
-      apps](https://devcenter.bitrise.io/en/getting-started/getting-started-with-flutter-apps.html).
+  release:
     steps:
     - git-clone@6: {}
     - flutter-installer@0:
         inputs:
         - is_update: 'false'
+    - file-downloader:
+        inputs:
+        - source: "$BITRISEIO_ANDROID_KEYSTORE_URL"
+        - destination: "$BITRISE_SOURCE_DIR/android/app/ueno-upload-keystore.jks"
+    - file-downloader@1:
+        inputs:
+        - destination: "$BITRISE_SOURCE_DIR/android/key.properties"
+        - source: "$BITRISEIO_KEY_PROPERTIES_URL"
+    - script@1:
+        inputs:
+        - content: |-
+            #!/usr/bin/env bash
+            # fail if any commands fails
+            set -e
+            # make pipelines' return status equal the last command to exit with a non-zero status, or zero if all commands exit successfully
+            set -o pipefail
+            # debug log
+            set -x
+
+            # write your script here
+            echo $HOME
+            echo $BITRISE_SOURCE_DIR
+            ls $BITRISE_SOURCE_DIR
+            ls $HOME
+    - flutter-build@0:
+        inputs:
+        - project_location: "$BITRISE_FLUTTER_PROJECT_LOCATION"
+        - platform: android
+        - android_additional_params: "--release"
+        - android_output_type: appbundle
+        - is_debug_mode: 'true'
     - cache-pull@2: {}
     - cache-push@2: {}
     - deploy-to-bitrise-io@2: {}
@@ -62,4 +68,4 @@ app:
   envs:
   - opts:
       is_expand: false
-    BITRISE_FLUTTER_PROJECT_LOCATION: .
+    BITRISE_FLUTTER_PROJECT_LOCATION: "."
