Update bitrise.yml

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -47,6 +47,20 @@ workflows:
     steps:
     - activate-ssh-key@4: {}
     - git-clone@7: {}
+    - script@1:
+        inputs:
+        - content: |
+            #!/usr/bin/env bash
+            # fail if any commands fails
+            set -e
+            # make pipelines' return status equal the last command to exit with a non-zero status, or zero if all commands exit successfully
+            set -o pipefail
+            # debug log
+            set -x
+
+            # write your script here
+            echo version code -- $BUILD_NUMBER
+            echo version name -- $BUILD_VERSION
   primary:
     description: |
       Builds project and runs tests.
